-- MySQL Script generated by MySQL Workbench
-- 05/30/20 00:34:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ZerarDengue
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ZerarDengue
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ZerarDengue` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
-- -----------------------------------------------------
-- Schema zeradengue
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema zeradengue
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zeradengue` DEFAULT CHARACTER SET latin1 ;
USE `ZerarDengue` ;

-- -----------------------------------------------------
-- Table `zeradengue`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zeradengue`.`usuario` (
  `Cod_Usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `Nome_Usuario` VARCHAR(50) NULL DEFAULT NULL,
  `E_mail_Usuario` VARCHAR(50) NULL DEFAULT NULL,
  `RG_Usuario` VARCHAR(50) NULL DEFAULT NULL,
  `CPF_Usuario` VARCHAR(50) NULL DEFAULT NULL,
  `Sexo` VARCHAR(45) NULL DEFAULT NULL,
  `Celular` VARCHAR(45) NULL,
  PRIMARY KEY (`Cod_Usuario`))
ENGINE = MyISAM
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `zeradengue`.`equipe_desinfeccao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zeradengue`.`equipe_desinfeccao` (
  `Id_equipe_desinfeccao` INT(11) NOT NULL AUTO_INCREMENT,
  `Nome_Funcionario` VARCHAR(50) NULL DEFAULT NULL,
  `E_mail_funcionario` VARCHAR(40) NULL DEFAULT NULL,
  PRIMARY KEY (`Id_equipe_desinfeccao`))
ENGINE = MyISAM
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `zeradengue`.`denuncia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zeradengue`.`denuncia` (
  `Id_Denuncia` INT(11) NOT NULL AUTO_INCREMENT,
  `Descricao_denuncia` TINYTEXT NULL DEFAULT NULL,
  `Tipo_Foco` VARCHAR(40) NULL DEFAULT NULL,
  `Data` VARCHAR(10) NULL DEFAULT NULL,
  `equipe_desinfeccao_Id_equipe_desinfeccao` INT(11) NOT NULL,
  PRIMARY KEY (`Id_Denuncia`, `equipe_desinfeccao_Id_equipe_desinfeccao`),
  INDEX `fk_denuncia_equipe_desinfeccao1_idx` (`equipe_desinfeccao_Id_equipe_desinfeccao` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ZerarDengue`.`Cadastrar_Denuncia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ZerarDengue`.`Cadastrar_Denuncia` (
  `idCadastrar_Denuncia` INT NOT NULL,
  `usuario_Cod_Usuario` INT(11) NOT NULL,
  `denuncia_Id_Denuncia` INT(11) NOT NULL,
  PRIMARY KEY (`idCadastrar_Denuncia`, `usuario_Cod_Usuario`, `denuncia_Id_Denuncia`),
  INDEX `fk_Cadastrar_Denuncia_usuario_idx` (`usuario_Cod_Usuario` ASC),
  INDEX `fk_Cadastrar_Denuncia_denuncia1_idx` (`denuncia_Id_Denuncia` ASC),
  CONSTRAINT `fk_Cadastrar_Denuncia_usuario`
    FOREIGN KEY (`usuario_Cod_Usuario`)
    REFERENCES `zeradengue`.`usuario` (`Cod_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cadastrar_Denuncia_denuncia1`
    FOREIGN KEY (`denuncia_Id_Denuncia`)
    REFERENCES `zeradengue`.`denuncia` (`Id_Denuncia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ZerarDengue`.`Estado_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ZerarDengue`.`Estado_usuario` (
  `idEstado_usuario` INT NOT NULL,
  `UF` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstado_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ZerarDengue`.`Cidade_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ZerarDengue`.`Cidade_usuario` (
  `idCidade_usuario` INT NOT NULL,
  `Nome_Cidade` VARCHAR(45) NULL,
  `CEP` VARCHAR(45) NULL,
  `Estado_usuario_idEstado_usuario` INT NOT NULL,
  PRIMARY KEY (`idCidade_usuario`, `Estado_usuario_idEstado_usuario`),
  INDEX `fk_Cidade_usuario_Estado_usuario1_idx` (`Estado_usuario_idEstado_usuario` ASC),
  CONSTRAINT `fk_Cidade_usuario_Estado_usuario1`
    FOREIGN KEY (`Estado_usuario_idEstado_usuario`)
    REFERENCES `ZerarDengue`.`Estado_usuario` (`idEstado_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zeradengue`.`Enderco_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zeradengue`.`Enderco_usuario` (
  `Id_Enderco_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `Nome_Da_Rua` VARCHAR(50) NULL DEFAULT NULL,
  `Numero_Da_Rua` INT(11) NULL,
  `Complemento` VARCHAR(40) NULL DEFAULT NULL,
  `CEP` VARCHAR(20) NULL DEFAULT NULL,
  `UF` VARCHAR(10) NULL DEFAULT NULL,
  `Cidade_usuario_idCidade_usuario` INT NOT NULL,
  PRIMARY KEY (`Id_Enderco_usuario`, `Cidade_usuario_idCidade_usuario`),
  INDEX `fk_Enderco_usuario_Cidade_usuario1_idx` (`Cidade_usuario_idCidade_usuario` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ZerarDengue`.`Usu_perten_localização`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ZerarDengue`.`Usu_perten_localização` (
  `idUsu_perten_localização` INT NOT NULL,
  `usuario_Cod_Usuario` INT(11) NOT NULL,
  `Enderco_usuario_Id_Enderco_usuario` INT(11) NOT NULL,
  PRIMARY KEY (`idUsu_perten_localização`, `usuario_Cod_Usuario`, `Enderco_usuario_Id_Enderco_usuario`),
  INDEX `fk_Usu_perten_localização_usuario1_idx` (`usuario_Cod_Usuario` ASC),
  INDEX `fk_Usu_perten_localização_Enderco_usuario1_idx` (`Enderco_usuario_Id_Enderco_usuario` ASC),
  CONSTRAINT `fk_Usu_perten_localização_usuario1`
    FOREIGN KEY (`usuario_Cod_Usuario`)
    REFERENCES `zeradengue`.`usuario` (`Cod_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usu_perten_localização_Enderco_usuario1`
    FOREIGN KEY (`Enderco_usuario_Id_Enderco_usuario`)
    REFERENCES `zeradengue`.`Enderco_usuario` (`Id_Enderco_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zeradengue`.`fiscal_de_rua`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zeradengue`.`fiscal_de_rua` (
  `Id_fiscal_de_rua` INT(11) NOT NULL AUTO_INCREMENT,
  `Nome_Fiscal` VARCHAR(50) NULL DEFAULT NULL,
  `E_Mail_Fiscal` VARCHAR(40) NULL DEFAULT NULL,
  `telefone_fiscal` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Id_fiscal_de_rua`),
  INDEX `telefone_fiscal` (`telefone_fiscal` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ZerarDengue`.`denuncia_fiscal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ZerarDengue`.`denuncia_fiscal` (
  `iddenuncia_fiscal` INT NOT NULL,
  `denuncia_Id_Denuncia` INT(11) NOT NULL,
  `fiscal_de_rua_Id_fiscal_de_rua` INT(11) NOT NULL,
  PRIMARY KEY (`iddenuncia_fiscal`, `denuncia_Id_Denuncia`, `fiscal_de_rua_Id_fiscal_de_rua`),
  INDEX `fk_denuncia_fiscal_denuncia1_idx` (`denuncia_Id_Denuncia` ASC),
  INDEX `fk_denuncia_fiscal_fiscal_de_rua1_idx` (`fiscal_de_rua_Id_fiscal_de_rua` ASC),
  CONSTRAINT `fk_denuncia_fiscal_denuncia1`
    FOREIGN KEY (`denuncia_Id_Denuncia`)
    REFERENCES `zeradengue`.`denuncia` (`Id_Denuncia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_denuncia_fiscal_fiscal_de_rua1`
    FOREIGN KEY (`fiscal_de_rua_Id_fiscal_de_rua`)
    REFERENCES `zeradengue`.`fiscal_de_rua` (`Id_fiscal_de_rua`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ZerarDengue`.`Estado_fabricante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ZerarDengue`.`Estado_fabricante` (
  `idEstado_fabricante` INT NOT NULL,
  `UF` VARCHAR(10) NULL,
  PRIMARY KEY (`idEstado_fabricante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ZerarDengue`.`Cidade_fabricante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ZerarDengue`.`Cidade_fabricante` (
  `idCidade_fabricante` INT NOT NULL,
  `Cidade_fabricante` VARCHAR(45) NULL,
  `CEP` VARCHAR(45) NULL,
  `Estado_fabricante_idEstado_fabricante` INT NOT NULL,
  PRIMARY KEY (`idCidade_fabricante`, `Estado_fabricante_idEstado_fabricante`),
  INDEX `fk_Cidade_fabricante_Estado_fabricante1_idx` (`Estado_fabricante_idEstado_fabricante` ASC),
  CONSTRAINT `fk_Cidade_fabricante_Estado_fabricante1`
    FOREIGN KEY (`Estado_fabricante_idEstado_fabricante`)
    REFERENCES `ZerarDengue`.`Estado_fabricante` (`idEstado_fabricante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ZerarDengue`.`Endereco_fabricante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ZerarDengue`.`Endereco_fabricante` (
  `idEndereco_fabricante` INT NOT NULL,
  `Rua` VARCHAR(45) NULL,
  `Bairro` VARCHAR(45) NULL,
  `numero` VARCHAR(45) NULL,
  `Complemento` VARCHAR(45) NULL,
  `Cidade_fabricante_idCidade_fabricante` INT NOT NULL,
  PRIMARY KEY (`idEndereco_fabricante`, `Cidade_fabricante_idCidade_fabricante`),
  INDEX `fk_Endereco_fabricante_Cidade_fabricante1_idx` (`Cidade_fabricante_idCidade_fabricante` ASC),
  CONSTRAINT `fk_Endereco_fabricante_Cidade_fabricante1`
    FOREIGN KEY (`Cidade_fabricante_idCidade_fabricante`)
    REFERENCES `ZerarDengue`.`Cidade_fabricante` (`idCidade_fabricante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ZerarDengue`.`Tipo_teleofone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ZerarDengue`.`Tipo_teleofone` (
  `idTipo_teleofone` INT NOT NULL,
  `Residencial` VARCHAR(45) NULL,
  `Celuar` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipo_teleofone`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ZerarDengue`.`Telefone_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ZerarDengue`.`Telefone_Usuario` (
  `idTelefone_Usuario` INT NOT NULL,
  `Telefone_Usuariocol` VARCHAR(45) NULL,
  `Numero_telefone` VARCHAR(45) NULL,
  `Tipo_teleofone_idTipo_teleofone` INT NOT NULL,
  PRIMARY KEY (`idTelefone_Usuario`, `Tipo_teleofone_idTipo_teleofone`),
  INDEX `fk_Telefone_Usuario_Tipo_teleofone1_idx` (`Tipo_teleofone_idTipo_teleofone` ASC),
  CONSTRAINT `fk_Telefone_Usuario_Tipo_teleofone1`
    FOREIGN KEY (`Tipo_teleofone_idTipo_teleofone`)
    REFERENCES `ZerarDengue`.`Tipo_teleofone` (`idTipo_teleofone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ZerarDengue`.`Tel_pert_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ZerarDengue`.`Tel_pert_usuario` (
  `idTel_pert_usuario` INT NOT NULL,
  `usuario_Cod_Usuario` INT(11) NOT NULL,
  `Telefone_Usuario_idTelefone_Usuario` INT NOT NULL,
  PRIMARY KEY (`idTel_pert_usuario`, `usuario_Cod_Usuario`, `Telefone_Usuario_idTelefone_Usuario`),
  INDEX `fk_Tel_pert_usuario_usuario1_idx` (`usuario_Cod_Usuario` ASC),
  INDEX `fk_Tel_pert_usuario_Telefone_Usuario1_idx` (`Telefone_Usuario_idTelefone_Usuario` ASC),
  CONSTRAINT `fk_Tel_pert_usuario_usuario1`
    FOREIGN KEY (`usuario_Cod_Usuario`)
    REFERENCES `zeradengue`.`usuario` (`Cod_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tel_pert_usuario_Telefone_Usuario1`
    FOREIGN KEY (`Telefone_Usuario_idTelefone_Usuario`)
    REFERENCES `ZerarDengue`.`Telefone_Usuario` (`idTelefone_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `zeradengue` ;

-- -----------------------------------------------------
-- Table `zeradengue`.`fabricante_pneus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zeradengue`.`fabricante_pneus` (
  `Cnpj_Fabricante_Pneus` VARCHAR(50) NOT NULL,
  `Razao_Social` VARCHAR(50) NULL,
  `Pessoa_de_Contato` VARCHAR(40) NULL DEFAULT NULL,
  `E_mail_Fabricante_Pneus` VARCHAR(45) NULL DEFAULT NULL,
  `denuncia_Id_Denuncia` INT(11) NOT NULL,
  `Endereco_fabricante_idEndereco_fabricante` INT NOT NULL,
  PRIMARY KEY (`Cnpj_Fabricante_Pneus`, `denuncia_Id_Denuncia`, `Endereco_fabricante_idEndereco_fabricante`),
  INDEX `fk_fabricante_pneus_denuncia1_idx` (`denuncia_Id_Denuncia` ASC),
  INDEX `fk_fabricante_pneus_Endereco_fabricante1_idx` (`Endereco_fabricante_idEndereco_fabricante` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `zeradengue`.`historico_denuncia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zeradengue`.`historico_denuncia` (
  `Id_Historico_denuncia` INT(11) NOT NULL,
  `usuario_Cod_Usuario` INT(11) NOT NULL,
  `denuncia_Id_Denuncia` INT(11) NOT NULL,
  PRIMARY KEY (`Id_Historico_denuncia`, `usuario_Cod_Usuario`, `denuncia_Id_Denuncia`),
  INDEX `fk_historico_denuncia_usuario1_idx` (`usuario_Cod_Usuario` ASC),
  INDEX `fk_historico_denuncia_denuncia1_idx` (`denuncia_Id_Denuncia` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
